import 'babel-polyfill';
import 'bootstrap';
import './module/utils';
import './module/gsap/custom-onscroll-animations';
// import './module/gsap/custom-onclick-animations';
import './module/gsap/custom-page-transitions';
import './module/gsap/custom-page-loaders';
import './module/gsap/custom-parallax-animations';
import './module/gsap/custom-parallax-3d';
import './module/gsap/custom-fullpage-animations-2';
import './module/page-barba';
