import 'babel-polyfill';
import 'bootstrap';
import './module/utils';
import './module/gsap/custom-onscroll-animations';
// import './module/gsap/custom-onclick-animations';
import './module/gsap/custom-page-transitions';
import './module/gsap/custom-page-loaders';
import './module/gsap/custom-parallax-animations';
// import './module/gsap/custom-popover-animations';
import './module/gsap/custom-text-effects';
// import './module/gsap/custom-smooth-scrolling';
import './module/gsap/custom-filter-effects';
import './module/gsap/custom-parallax-3d';
// import './module/gsap/custom-fullpage-animations-2';
import './module/page-barba';
